Repository hmcts/pip-channel-management, pull requests merged in 2022-09, with the labels that each got.

#39 Force upgrade snakeyaml version for CVE-2022-25857
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-39

#38 PUB-1521 Service-to-service fix
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/config/WebClientConfig.java
  src/test/java/uk/gov/hmcts/reform/pip/channel/management/config/WebClientCreationTest.java
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-38

#36 PUB-1476 Updated app insights name
  src/main/resources/application.yaml
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-36
