Repository hmcts/pip-channel-management, pull requests merged in 2023-06, with the labels that each got.

#194 PUB-1996 - Updated chart + suppressions
  build.gradle
  charts/pip-channel-management/Chart.yaml
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/config/AzureBlobTestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/config/SwaggerPublisherTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/ChannelManagementTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/GetWelcomeTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/config/AzureBlobConfiguration.java
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-194

#197 Suppress CVE-2023-34411
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-197

#196 PUB-1918 Add brackets to case sequence indicators
  src/functionalTest/java/uk/gov/hmcts/reform/pip/channel/management/controllers/PublicationManagementTest.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CopDailyCauseListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CrownDailyListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CrownFirmListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/EtDailyListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/EtFortnightlyPressListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/IacDailyListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesPublicListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/MagistratesStandardListSummaryConverter.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/CaseHelper.java
  src/main/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/TribunalNationalListHelper.java
  src/main/resources/templates/copDailyCauseList.html
  src/main/resources/templates/crownDailyList.html
  src/main/resources/templates/crownFirmList.html
  src/main/resources/templates/etDailyList.html
  src/main/resources/templates/etFortnightlyPressList.html
  src/main/resources/templates/iacDailyList.html
  src/main/resources/templates/magistratesPublicList.html
  src/main/resources/templates/magistratesStandardList.html
  src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/artefactsummary/CopDailyCauseListSummaryConverterTest.java
  src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/CaseHelperTest.java
  src/test/java/uk/gov/hmcts/reform/pip/channel/management/services/helpers/listmanipulation/CopListHelperTest.java
  src/test/resources/mocks/careStandardsList.json
  src/test/resources/mocks/civilAndFamilyDailyCauseList.json
  src/test/resources/mocks/civilDailyCauseList.json
  src/test/resources/mocks/copDailyCauseList.json
  src/test/resources/mocks/copDailyCauseListMissingRegion.json
  src/test/resources/mocks/copDailyCauseListMissingRegionalJoh.json
  src/test/resources/mocks/crownDailyList.json
  src/test/resources/mocks/crownFirmList.json
  src/test/resources/mocks/etDailyList.json
  src/test/resources/mocks/etFortnightlyPressList.json
  src/test/resources/mocks/familyDailyCauseList.json
  src/test/resources/mocks/iacDailyList.json
  src/test/resources/mocks/magistratesPublicList.json
  src/test/resources/mocks/magistratesStandardList.json
  src/test/resources/mocks/primaryHealthList.json
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-196

#198 PUB-1900 update Gradle to V8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-198

#201 Suppress CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-channel-management-pr-201
